version: '3'
services:
  db:
    image: mariadb:10
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=topsecret
      - MYSQL_DATABASE=curo
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  ldap:
    image: osixia/openldap:1.3.0
    ports:
      - 127.0.0.1:389:389
    environment:
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_DOMAIN=example.org
    volumes:
      - ./docker/local/ldif-files:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command:
      - --copy-service
